<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Tue Jan 22 2019 17:33:14 GMT+0000 (Coordinated Universal Time)). */
return array(
	'public/dist/rml_shortcode.js' => 'b11bb99e9ed47edf555bee678a8ec369',
	'public/dist/rml.js' => 'a7196cc443b83081663ba0401c8abde6',
	'public/dist/rml.css' => '75f088fffeba10f9394493135aec9b42',
	'public/dev/rml_shortcode.js' => '4238da510fdf1121dffa1efab9d6fbf1',
	'public/dev/rml.js' => 'a64692d7367bdf5167ac9f3193db068c',
	'public/dev/rml.css' => '8b01d58a5e307be1a68704f094aed381',
);
